### ISSUE TITLE
[BUG] SyntaxError: Invalid Syntax

### ISSUE THREAD

**Issue by shinkarom** [AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients#1]
Error loading script: aesthetic.py
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/scripts.py", line 157, in load_scripts
    compiled = compile(text, scriptfile.path, 'exec')
  File "/content/stable-diffusion-webui/extensions/aesthetic-gradients/scripts/aesthetic.py", line 72
    return *updates, res
           ^
SyntaxError: invalid syntax

Using Colab StableDiffusionUI-Voldemort V1.2

**Comment by shinkarom** [comment]
The line needs to be updated to `return [*updates,res]`

**Comment by AUTOMATIC1111** [comment]
works for me but ok
