### ISSUE TITLE
After upgrading the plug-in, this kind of problem appeared, I don't know what's going on

### ISSUE THREAD

**Issue by Myra009** [AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients#22]
Error loading script: aesthetic.py
Traceback (most recent call last):
  File "D:\SD20\stable-diffusion-webui_22-12-25\stable-diffusion-webui_22-12-25\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\SD20\stable-diffusion-webui_22-12-25\stable-diffusion-webui_22-12-25\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\SD20\stable-diffusion-webui_22-12-25\stable-diffusion-webui_22-12-25\extensions\stable-diffusion-webui-aesthetic-gradients\scripts\aesthetic.py", line 98, in <module>
    script_callbacks.on_script_unloaded(on_script_unloaded)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_script_unloaded'

**Comment by nabukhod** [comment]
I encountered the same error.. any solution yet?
