### ISSUE TITLE
Error with SD XL

### ISSUE THREAD

**Issue by LieDeath** [AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients#30]
i can't load it with sd xl apply. seems missing model key is the error origin, due to model structure changed
```
*** Error executing callback model_loaded_callback for D:\AI6\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-gradients\scripts\aesthetic.py
    Traceback (most recent call last):
      File "D:\AI6\stable-diffusion-webui\modules\script_callbacks.py", line 143, in model_loaded_callback
        c.callback(sd_model)
      File "D:\AI6\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-gradients\scripts\aesthetic.py", line 40, in on_model_loaded
        aesthetic.process_tokens = sd_model.cond_stage_model.process_tokens
      File "D:\AI6\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'GeneralConditioner' object has no attribute 'process_tokens'

---
```

**Comment by tangcan1600** [comment]
I have the same problem. Have you solved it yet

**Comment by MKC-Mankii** [comment]
same with you, I can't load sdxl1.0 model

![image](https://github.com/AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients/assets/9945662/df69019c-1b3e-421b-9399-23fce3c8e9c1)

**Comment by cvar66** [comment]
I wish this still worked with SDXL...
