### ISSUE TITLE
Error with loading any embeddings using ROCm running natively

### ISSUE THREAD

**Issue by mohmmdgaber** [AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients#5]
Getting this error when trying to load any Aesthetic imgs embedding

```
Aesthetic optimization:   0%|                                                                                                                                                                                             | 0/5 [00:00<?, ?it/s]
Error completing request
Arguments: ('test prompt', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, 0.9, 5, '0.0001', False, 'dreambooth', '', 0.1, False, False, False, None, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
  File "/home/mo/Stable-diff/stable-diffusion-webui/modules/ui.py", line 221, in f
    res = list(func(*args, **kwargs))
  File "/home/mo/Stable-diff/stable-diffusion-webui/webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "/home/mo/Stable-diff/stable-diffusion-webui/modules/txt2img.py", line 48, in txt2img
    processed = process_images(p)
  File "/home/mo/Stable-diff/stable-diffusion-webui/modules/processing.py", line 426, in process_images
    uc = prompt_parser.get_learned_conditioning(shared.sd_model, len(prompts) * [p.negative_prompt], p.steps)
  File "/home/mo/Stable-diff/stable-diffusion-webui/modules/prompt_parser.py", line 138, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "/home/mo/Stable-diff/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 558, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "/home/mo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1363, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mo/Stable-diff/stable-diffusion-webui/modules/sd_hijack.py", line 334, in forward
    z1 = self.process_tokens(tokens, multipliers)
  File "/home/mo/Stable-diff/stable-diffusion-webui/extensions/aesthetic-gradients/aesthetic_clip.py", line 233, in __call__
    sim = text_embs @ img_embs.T
AttributeError: 'dict' object has no attribute 'T'



```

**Comment by initialxy** [comment]
I got the same error. However looking just above these console outputs, I saw this.

    ...
     Exception: bad file inside /home/initialxy/git/stable-diffusion-webui/extensions/aesthetic-gradients/aesthetic_embeddings/my.pt: my/data.pkl


    The file may be malicious, so the program is not going to read it.
    You can skip this check with --disable-safe-unpickle commandline argument.

So I launched `launcher.py` with `--disable-safe-unpickle` and it worked.
